name: Build, Test, and Deploy Node.js Express Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fix mocha permissions
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/*.xml

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build || true

      # This step configures the Docker daemon on the GitHub Actions runner
      # to allow insecure HTTP communication with your registry.
      # WARNING: This is a security risk and not recommended for production.
      - name: Configure insecure Docker registry ⚠️
        run: |
          echo '{"insecure-registries": ["37.27.196.138:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          echo "Docker daemon restarted. Verifying insecure registry setting:"
          docker info | grep "Insecure Registries" # Verify the setting

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_VERSION=${{ secrets.NODE_VERSION }} \
            -t 37.27.196.138:5000/myapp:${{ github.sha }} .

      - name: Push Docker image to local registry
        run: |
          echo "Pushing image to 37.27.196.138:5000"
          docker push 37.27.196.138:5000/myapp:${{ github.sha }}

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            export APP_VERSION=${{ github.sha }}
            export APP_PORT=${{ secrets.APP_PORT }}
            export POSTGRES_VERSION=${{ secrets.POSTGRES_VERSION }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export REGISTRY_HOST="37.27.196.138:5000" # Define registry host for docker-compose

            echo "Using APP_VERSION=${APP_VERSION}"
            echo "Using REGISTRY_HOST=${REGISTRY_HOST}"

            # Create docker-compose.yml
            cat << EOF > /root/docker-compose.yml
            version: '3.8'
            services:
              app:
                image: ${REGISTRY_HOST}/myapp:\${APP_VERSION}
                ports:
                  - "\${APP_PORT}:3000"
                environment:
                  - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
                depends_on:
                  - postgres
                restart: always
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
                  interval: 30s
                  timeout: 3s
              postgres:
                image: postgres:\${POSTGRES_VERSION}
                environment:
                  - POSTGRES_DB=mydb
                  - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
                ports:
                  - "5432:5432" # Changed from 5433:5432 in previous examples
                restart: always
                volumes:
                  - postgres_data:/var/lib/postgresql/data
            volumes:
              postgres_data:
            EOF

            echo "DEBUG: docker pull ${REGISTRY_HOST}/myapp:\${APP_VERSION}"
            # Ensure the VPS Docker daemon also allows insecure registries if your registry is HTTP
            # If your VPS is pulling from an insecure registry, you might need to configure its daemon.json too.
            # This is beyond the scope of this workflow, but keep it in mind if pulls fail.
            if ! docker pull ${REGISTRY_HOST}/myapp:${APP_VERSION}; then
              echo "Failed to pull new image" >&2
              exit 1
            fi

            docker compose -f /root/docker-compose.yml down || true

            if ! docker compose -f /root/docker-compose.yml up -d; then
              echo "Deployment failed. Rolling back..." >&2
              # Note: Rollback here uses a PREVIOUS_APP_VERSION secret.
              # You need to ensure this secret is correctly managed (e.g., updated after a successful deploy).
              # A more robust rollback might store history on the VPS.
              if [ -n "${{ secrets.PREVIOUS_APP_VERSION }}" ]; then
                export APP_VERSION=${{ secrets.PREVIOUS_APP_VERSION }}
                docker compose -f /root/docker-compose.yml up -d
                echo "Rolled back to \$APP_VERSION"
                exit 1
              else
                echo "No previous version available for rollback" >&2
                exit 1
              fi
            fi

            # Clean up old images, keeping the latest 5 (current + 4 previous)
            docker images ${REGISTRY_HOST}/myapp --format '{{.Tag}}' | sort -r | tail -n +6 | xargs -I {} docker rmi ${REGISTRY_HOST}/myapp:{} || true

            # Store the current version for potential future rollbacks
            echo "\$APP_VERSION" > /root/previous_version.txt