services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_ENABLED=false
    volumes:
      - registry-data:/var/lib/registry
    restart: always
volumes:
  registry-data:
