name: Build, Test, and Deploy Node.js Express Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fix mocha permissions
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/*.xml

  deploy-registry:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: SSH into VPS and deploy registry
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "--- Starting Registry Deployment Setup ---"
            # Install dependencies
            sudo apt update
            sudo apt install -y curl git docker.io docker-compose

            # Enable and start Docker
            sudo systemctl enable docker
            sudo systemctl start docker

            # Configure insecure registry (using your provided IP)
            # This is crucial for Docker to allow pushing/pulling from your local registry
            echo '{"insecure-registries": ["37.27.196.198:5000"]}' | sudo tee /etc/docker/daemon.json # Updated IP
            sudo systemctl restart docker
            echo "Docker daemon configured for insecure registry and restarted."

            # Define registry path
            REGISTRY_DIR="/root/registry"
            REGISTRY_COMPOSE_FILE="$REGISTRY_DIR/docker-compose.yml"
            REGISTRY_AUTH_DIR="$REGISTRY_DIR/auth"
            REGISTRY_IP="37.27.196.198" # Updated IP

            # Ensure registry directory and auth directory exist
            mkdir -p "$REGISTRY_AUTH_DIR"

            # Generate registry docker-compose.yml
            cat << EOF > "$REGISTRY_COMPOSE_FILE"
            version: '3.8'
            services:
              registry:
                image: registry:2
                ports:
                  - "5000:5000"
                environment:
                  - REGISTRY_HTTP_ADDR=0.0.0.0:5000
                  - REGISTRY_HTTP_TLS_ENABLED=false
                  - REGISTRY_AUTH=htpasswd
                  - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
                  - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
                volumes:
                  - registry-data:/var/lib/registry
                  - $REGISTRY_AUTH_DIR:/auth # Mount auth directory
                restart: always
            volumes:
              registry-data:
            EOF
            echo "Registry docker-compose.yml created."

            # Create htpasswd for registry authentication
            # Using secrets for username/password
            docker run --entrypoint htpasswd httpd:2 -Bbn "${{ secrets.DOCKER_USERNAME }}" "${{ secrets.DOCKER_PASSWORD }}" > "$REGISTRY_AUTH_DIR/htpasswd"
            echo "htpasswd file created for registry authentication."

            # Stop and remove old registry containers before starting a new one
            docker compose -f "$REGISTRY_COMPOSE_FILE" down || true
            echo "Previous registry containers stopped and removed."

            # Start registry with retries
            echo "Starting registry..."
            for attempt in {1..3}; do
              docker compose -f "$REGISTRY_COMPOSE_FILE" up -d
              # Check if container is running after up command
              if docker ps --filter "ancestor=registry:2" --filter "status=running" | grep -q "registry"; then
                echo "Registry container appears to be running."
                break
              else
                echo "Registry container not running after 'up' command. Checking logs for details..." >&2
                docker logs $(docker ps -a --filter "ancestor=registry:2" -q --latest) || true # Show logs of the latest registry container
              fi
              echo "Registry start attempt $attempt failed, retrying..." >&2
              sleep 5
            done || { echo "Registry failed to start after multiple attempts!"; exit 1; }
            echo "Registry started successfully."

            # Verify registry is running and accessible (using localhost for internal check and authentication)
            echo "Verifying registry health using localhost:5000 with authentication..."
            if ! curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" http://localhost:5000/v2/ | grep -q '{}'; then
              echo "Registry failed health check on HTTP at localhost:5000" >&2
              # Add more debug info if health check fails
              echo "Current docker ps output:" >&2
              docker ps -a >&2
              echo "Current docker logs for registry:" >&2
              docker logs $(docker ps -a --filter "ancestor=registry:2" -q --latest) >&2
              exit 1
            fi
            echo "Registry health check passed."

            # Configure firewall to allow registry traffic
            sudo ufw allow 5000
            echo "Firewall configured to allow port 5000."
            echo "--- Registry Deployment Complete ---"

  build-and-deploy:
    needs: deploy-registry # Ensure registry is up before deploying app
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # NEW STEP: Configure Buildx builder to allow insecure registries
      - name: Configure Buildx for Insecure Registry
        run: |
          BUILDER_NAME="mybuilder"
          REGISTRY_IP="37.27.196.198" # Ensure this matches your registry's IP

          # Check if the builder exists and if it supports insecure registries
          # If it doesn't exist or isn't configured, create/recreate it
          if ! docker buildx inspect $BUILDER_NAME &>/dev/null || ! docker buildx inspect $BUILDER_NAME | grep -q "insecure-registry.*${REGISTRY_IP}:5000"; then
            echo "Creating/reconfiguring Buildx builder '$BUILDER_NAME' with insecure registry support..."
            # Use --append if you want to add to an existing builder, or just create/recreate
            docker buildx create --name $BUILDER_NAME --use --driver docker-container --buildkitd-flags "--allow-insecure-entitlement"
            docker buildx inspect --bootstrap # Ensures the builder is running
          else
            echo "Buildx builder '$BUILDER_NAME' already configured for insecure registry."
          fi

      - name: Configure Docker for insecure registry (on runner for build/push)
        run: |
          echo '{"insecure-registries": ["37.27.196.198:5000"]}' | sudo tee /etc/docker/daemon.json # Updated IP
          sudo systemctl restart docker
          echo "Runner's Docker daemon configured for insecure registry."

      - name: Log in to local Docker registry (on runner for push)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Logging into local registry 37.27.196.198:5000..." # Updated IP
          for attempt in {1..3}; do
            echo "$DOCKER_PASSWORD" | docker login 37.27.196.198:5000 -u "$DOCKER_USERNAME" --password-stdin && break # Updated IP
            echo "Login attempt $attempt failed, retrying..." >&2
            sleep 5
          done || { echo "Failed to log in to local registry on runner!"; exit 1; }
          echo "Logged into local registry."

      - name: Build and Push Docker image to registry for multiple platforms
        run: |
          LOCAL_REGISTRY_IMAGE="37.27.196.198:5000/myapp" # Updated IP
          APP_BUILD_TAG="${{ github.sha }}"
          echo "Building and pushing multi-platform Docker image: ${LOCAL_REGISTRY_IMAGE}:${APP_BUILD_TAG}"
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            --build-arg NODE_VERSION=${{ secrets.NODE_VERSION }} \
            -t "${LOCAL_REGISTRY_IMAGE}:${APP_BUILD_TAG}" \
            --push . || { echo "Multi-platform Docker image build and push failed!"; exit 1; } # Removed --allow-insecure-entitlement from here
          echo "Multi-platform Docker image built and pushed successfully."

      - name: SSH into VPS and deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "--- Starting Application Deployment on VPS ---"
            APP_DIR="/root/express-demo" # Consistent application directory
            PROJECT_NAME="express-demo" # Docker Compose project name

            # 1. Aggressive Cleanup of application-related containers and processes
            echo "--- Starting Aggressive Application Cleanup ---"
            cd /root # Ensure we are not inside the app directory for initial broad commands

            # Stop and remove containers by project name (most common for compose)
            echo "Attempting docker compose down for project: $PROJECT_NAME..."
            if [ -d "$APP_DIR" ] && [ -f "$APP_DIR/docker-compose.yml" ]; then
                cd "$APP_DIR"
                # Use --timeout 0 for immediate stop, --rmi all to remove images, --volumes to remove named volumes
                docker compose -p "$PROJECT_NAME" -f docker-compose.yml down --timeout 0 --rmi all --volumes --remove-orphans || true
                echo "docker compose down completed for $PROJECT_NAME."
                cd /root # Change back to root after docker compose down
            else
                echo "App directory or docker-compose.yml not found, skipping docker compose down."
            fi

            # Force stop/remove any remaining containers related to app or postgres images
            echo "Force stopping and removing any lingering app or postgres containers..."
            # Get IDs of containers derived from your app image or postgres image
            OLD_APP_CONTAINERS=$(docker ps -a -q --filter "ancestor=37.27.196.198:5000/myapp" || true) # Updated IP
            OLD_POSTGRES_CONTAINERS=$(docker ps -a -q --filter "ancestor=postgres" || true)

            if [ -n "$OLD_APP_CONTAINERS" ]; then
                echo "Stopping and removing old app containers: $OLD_APP_CONTAINERS"
                docker stop $OLD_APP_CONTAINERS || true
                docker rm -f $OLD_APP_CONTAINERS || true # Use -f for force removal
            fi
            if [ -n "$OLD_POSTGRES_CONTAINERS" ]; then
                echo "Stopping and removing old postgres containers: $OLD_POSTGRES_CONTAINERS"
                docker stop $OLD_POSTGRES_CONTAINERS || true
                docker rm -f $OLD_POSTGRES_CONTAINERS || true # Use -f for force removal
            fi

            # Aggressively kill any process holding the ports (last resort and primary fix for stubborn issues)
            echo "Checking and attempting to kill any process still holding ports ${{ secrets.APP_PORT }} or 5433..."
            LSOF_PIDS=$(sudo lsof -t -i :${{ secrets.APP_PORT }} -i :5433 | grep -v "^$" || true)

            if [ -n "$LSOF_PIDS" ]; then
                echo "Found processes on ports ${{ secrets.APP_PORT }} or 5433 (PIDs: $LSOF_PIDS). Attempting to kill them..."
                sudo kill -9 $LSOF_PIDS || true # Force kill
                sleep 5 # Initial small sleep
                echo "Confirmed killed processes on ports ${{ secrets.APP_PORT }} or 5433."
            else
                echo "No processes found holding ports ${{ secrets.APP_PORT }} or 5433."
            fi
            echo "--- Aggressive Application Cleanup Complete ---"

            # --- Ensure Ports are Truly Free Before Deployment (Robust Check) ---
            echo "Checking and waiting for ports ${{ secrets.APP_PORT }} and 5433 to be free..."
            PORT_CHECK_COUNT=0
            MAX_PORT_CHECKS=10 # Check up to 10 times
            PORT_CHECK_INTERVAL=10 # Wait 10 seconds between checks

            while [ "$PORT_CHECK_COUNT" -lt "$MAX_PORT_CHECKS" ]; do
                # Check for any process holding either port
                ACTIVE_PORTS=$(sudo lsof -i :${{ secrets.APP_PORT }} -i :5433 | grep LISTEN | awk '{print $1":"$9}' | xargs || true)

                if [ -z "$ACTIVE_PORTS" ]; then
                    echo "Ports ${{ secrets.APP_PORT }} and 5433 are free."
                    break # Ports are free, exit loop
                else
                    echo "Ports still in use by: $ACTIVE_PORTS. Retrying in $PORT_CHECK_INTERVAL seconds..." >&2
                    # Try to kill if it's docker-proxy or any related lingering process
                    LSOF_PIDS=$(sudo lsof -t -i :${{ secrets.APP_PORT }} -i :5433 || true)
                    if [ -n "$LSOF_PIDS" ]; then
                        echo "Attempting to kill processes: $LSOF_PIDS" >&2
                        sudo kill -9 $LSOF_PIDS || true
                    fi
                    sleep "$PORT_CHECK_INTERVAL"
                    PORT_CHECK_COUNT=$((PORT_CHECK_COUNT + 1))
                fi
            done

            if [ "$PORT_CHECK_COUNT" -eq "$MAX_PORT_CHECKS" ]; then
                echo "ERROR: Ports ${{ secrets.APP_PORT }} or 5433 are still in use after multiple checks. Aborting deployment." >&2
                exit 1
            fi
            echo "Ports are confirmed free. Resuming deployment."
            # --- End Port Check ---

            # Clone or update repository to ensure the latest docker-compose.yml is present
            echo "Updating application repository..."
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/${{ github.repository }} "$APP_DIR"
            fi
            cd "$APP_DIR"
            git reset --hard
            git clean -fd
            git pull origin master
            echo "Application repository updated."

            # Log in to local registry on VPS (for pulling app image)
            echo "Logging into local registry on VPS..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login 37.27.196.198:5000 -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || { echo "Docker login on VPS failed!"; exit 1; } # Updated IP
            echo "Logged into local registry on VPS."

            # Export environment variables for docker-compose to use (APP_VERSION, APP_PORT, POSTGRES_*)
            export APP_VERSION=${{ github.sha }}
            export APP_PORT=${{ secrets.APP_PORT }}
            export POSTGRES_VERSION=${{ secrets.POSTGRES_VERSION }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

            # Configure firewall to allow app and postgres traffic
            echo "Configuring firewall for application ports..."
            sudo ufw allow ${{ secrets.APP_PORT }}
            sudo ufw allow 5433
            echo "Firewall configured."

            # Deploy new version with retries
            echo "Deploying new application version with docker-compose..."
            for attempt in {1..3}; do
              # Ensure we're in the right directory for docker compose
              cd "$APP_DIR"
              docker compose -p "$PROJECT_NAME" -f docker-compose.yml up -d && break
              echo "Deployment attempt $attempt failed, retrying..." >&2
              sleep 15
            done || { echo "Application deployment failed after multiple attempts!"; exit 1; }
            echo "Application deployed successfully."

            # Verification and Rollback
            echo "--- Starting Application Verification ---"
            sleep 10 # Give app time to start
            if ! curl -s http://localhost:${{ secrets.APP_PORT }}/health | grep -q "ok"; then
              echo "Deployment failed health check. Rolling back..." >&2
              PREV_VERSION=$(cat /root/previous_version.txt || echo "")
              if [ -n "$PREV_VERSION" ]; then
                export APP_VERSION="$PREV_VERSION" # Set APP_VERSION for rollback
                echo "Attempting to pull and roll back to 37.27.196.198:5000/myapp:$PREV_VERSION from local registry" # Updated IP
                # Ensure we are in the app directory for rollback compose commands
                cd "$APP_DIR"
                docker compose -p "$PROJECT_NAME" -f docker-compose.yml pull app || { echo "Failed to pull previous app image for rollback!"; exit 1; }
                docker compose -p "$PROJECT_NAME" -f docker-compose.yml up -d || { echo "Failed to deploy previous version during rollback!"; exit 1; }
                echo "Rolled back to $PREV_VERSION"
                exit 1 # Exit with error code to indicate rollback happened
              else
                echo "No previous version available for rollback. Manual intervention required." >&2
                exit 1
              fi
            fi
            echo "--- Application Verification Successful ---"

            # Post-Deployment Cleanup
            echo "--- Starting Post-Deployment Cleanup ---"
            # Clean up old images (keep last 5). Use the full local registry image name.
            APP_IMAGE_FULL_NAME="37.27.196.198:5000/myapp" # Updated IP
            docker images "$APP_IMAGE_FULL_NAME" --format '{{.Tag}}' | sort -r | tail -n +6 | xargs -r -I {} docker rmi "$APP_IMAGE_FULL_NAME":{} || true
            echo "Old Docker application images cleaned up."

            # Save current version for future rollback
            echo "${{ github.sha }}" > /root/previous_version.txt
            echo "Current version (${{ github.sha }}) saved for future rollback."
            echo "--- Post-Deployment Cleanup Complete ---"