name: Build, Test, and Deploy Node.js Express Demo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fix mocha permissions
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/*.xml

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build || true

      - name: Log in to Docker registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login 37.27.196.138:5000 -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_VERSION=${{ secrets.NODE_VERSION }} \
            -t 37.27.196.138:5000/myapp:${{ github.sha }} .

      - name: Push Docker image to local registry
        run: |
          echo "Pushing image to 37.27.196.138:5000"
          docker push 37.27.196.138:5000/myapp:${{ github.sha }}

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            export APP_VERSION=${{ github.sha }}
            export APP_PORT=${{ secrets.APP_PORT }}
            export POSTGRES_VERSION=${{ secrets.POSTGRES_VERSION }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

            echo "Using APP_VERSION=${APP_VERSION}"

            cat << EOF > /root/docker-compose.yml
            version: '3.8'
            services:
              app:
                image: 37.27.196.138:5000/myapp:\${APP_VERSION}
                ports:
                  - "\${APP_PORT}:3000"
                environment:
                  - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
                depends_on:
                  - postgres
                restart: always
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
                  interval: 30s
                  timeout: 3s
              postgres:
                image: postgres:\${POSTGRES_VERSION}
                environment:
                  - POSTGRES_DB=mydb
                  - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
                ports:
                  - "5433:5432"
                restart: always
                volumes:
                  - postgres_data:/var/lib/postgresql/data
            volumes:
              postgres_data:
            EOF

            echo "Pulling new image 37.27.196.138:5000/myapp:\${APP_VERSION}"
            if ! docker pull 37.27.196.138:5000/myapp:\$APP_VERSION; then
              echo "Failed to pull new image" >&2
              exit 1
            fi

            docker compose -f /root/docker-compose.yml down || true

            if ! docker compose -f /root/docker-compose.yml up -d; then
              echo "Deployment failed. Rolling back..." >&2
              if [ -n "${{ secrets.PREVIOUS_APP_VERSION }}" ]; then
                export APP_VERSION=${{ secrets.PREVIOUS_APP_VERSION }}
                docker compose -f /root/docker-compose.yml up -d
                echo "Rolled back to \$APP_VERSION"
                exit 1
              else
                echo "No previous version available for rollback" >&2
                exit 1
              fi
            fi

            docker images 37.27.196.138:5000/myapp --format '{{.Tag}}' | sort -r | tail -n +6 | xargs -I {} docker rmi 37.27.196.138:5000/myapp:{} || true

            echo "\$APP_VERSION" > /root/previous_version.txt
